"""Build/refresh the OKF (Open Knowledge Format) LLM-Wiki under knowledge/.

One interlinked, machine-editable markdown page per NBA player in the
dataset (1996-97 onward), plus archetype and position hub pages and an
index. Pages are two-layer:

  - AUTO layer  — between okf:auto markers; regenerated from
    assets/vectors.json on every run. Never edit by hand.
  - CURATED layer — everything below the end marker; preserved verbatim
    across regenerations. Humans and LLM agents extend pages here.

Idempotent: re-running refreshes the auto layer and index/hubs, touching
nothing curated. See knowledge/OKF.md for the format contract.

Run:  python pipeline/build_wiki.py
"""
from __future__ import annotations

import datetime
import json
import re
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
VECTORS = ROOT / "assets" / "vectors.json"
KNOW = ROOT / "knowledge"

AUTO_BEGIN = "<!-- okf:auto:begin — regenerated by pipeline/build_wiki.py; do not edit this block -->"
AUTO_END = "<!-- okf:auto:end — curated layer below; humans and LLM agents extend the page here -->"

TODAY = datetime.date.today().isoformat()
NEIGHBORS = 6


def slugify(name: str) -> str:
    """Must match playerSlug() in assets/game.js."""
    s = unicodedata.normalize("NFD", name)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def sig(z: float) -> str:
    return ("+" if z >= 0 else "−") + f"{abs(z):.1f}σ"


def top_traits(v, labels, n=3, sign=1):
    order = sorted(range(len(v)), key=lambda i: -sign * v[i])
    return [(labels[i], v[i]) for i in order[:n] if sign * v[i] > 0]


def wl(slug: str, name: str) -> str:
    return f"[[{slug}|{name}]]"


def split_curated(path: Path) -> str | None:
    """Return the curated tail of an existing page, or None."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    idx = text.find(AUTO_END)
    if idx < 0:
        return None
    return text[idx + len(AUTO_END):].lstrip("\n")


DEFAULT_CURATED = """## Notes

<!-- Curated layer. Add scouting notes, history, film observations,
     corrections, and further [[wikilinks]] here. The generator never
     touches anything below the auto end marker. -->
"""


def main() -> None:
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    labels = [data["featureLabels"][f] for f in data["features"]]
    clusters = data["clusters"]
    positions = data.get("positions", [])
    players = data["players"]

    # ---- group player-seasons by name (the dataset carries no person id;
    #      same-name players are flagged, see `ambiguous`) ----
    by_name: dict[str, list[dict]] = defaultdict(list)
    for p in players:
        by_name[p["name"]].append(p)

    careers = {}
    for name, rows in by_name.items():
        rows.sort(key=lambda r: r["season"])
        seasons = [r["season"] for r in rows]
        ambiguous = len(seasons) != len(set(seasons))
        mean_v = np.mean([r["v"] for r in rows], axis=0)
        # signature season: the most extreme statistical identity
        sig_row = max(rows, key=lambda r: float(np.linalg.norm(r["v"])))
        pos_seen = [positions[r["p"]] for r in rows if positions and r.get("p", -1) >= 0]
        arch_seen = [clusters[r["c"]] for r in rows]
        careers[name] = {
            "slug": slugify(name),
            "rows": rows,
            "mean_v": mean_v,
            "sig_row": sig_row,
            "positions": [p for p, _ in Counter(pos_seen).most_common()],
            "archetypes": [a for a, _ in Counter(arch_seen).most_common()],
            "ambiguous": ambiguous,
        }

    # slug collisions across *different* names (extremely rare) -> suffix
    used: dict[str, str] = {}
    for name, c in sorted(careers.items()):
        if c["slug"] in used and used[c["slug"]] != name:
            c["slug"] = c["slug"] + "-" + slugify(c["rows"][0]["season"])
        used[c["slug"]] = name

    # ---- nearest statistical neighbors on career-mean vectors ----
    names = sorted(careers)
    M = np.array([careers[n]["mean_v"] for n in names])
    Mn = M / np.maximum(np.linalg.norm(M, axis=1, keepdims=True), 1e-9)
    S = Mn @ Mn.T
    np.fill_diagonal(S, -2)
    for i, n in enumerate(names):
        idxs = np.argsort(-S[i])[:NEIGHBORS]
        careers[n]["neighbors"] = [(names[j], float(S[i, j])) for j in idxs]

    (KNOW / "players").mkdir(parents=True, exist_ok=True)
    (KNOW / "archetypes").mkdir(exist_ok=True)
    (KNOW / "positions").mkdir(exist_ok=True)

    # ---- player pages ----
    n_new = n_updated = 0
    for name in names:
        c = careers[name]
        rows = c["rows"]
        path = KNOW / "players" / (c["slug"] + ".md")
        curated = split_curated(path)
        is_new = curated is None

        hi = top_traits(c["mean_v"], labels, 3, +1)
        lo = top_traits(-c["mean_v"], labels, 2, +1)
        span = f"{rows[0]['season']} – {rows[-1]['season']}"

        fm = [
            "---",
            "okf: 1",
            "kind: player",
            f"id: {c['slug']}",
            f"name: \"{name}\"",
            f"seasons_charted: {len(rows)}",
            f"span: {span}",
            f"positions: [{', '.join(c['positions']) or 'unlisted'}]",
            f"archetypes: [{'; '.join(c['archetypes'][:2])}]",
        ]
        if c["ambiguous"]:
            fm.append("ambiguous: true  # duplicate name+season rows — likely two different players share this name")
        fm += [f"updated: {TODAY}", "---"]

        body = ["", f"# {name}", "", AUTO_BEGIN, ""]
        id_bits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in hi)
        lo_bits = " · ".join(f"{lbl} {sig(z * -1)}" for lbl, z in lo)
        body.append(f"**Vector identity (career mean vs era):** {id_bits}" +
                    (f" — thin: {lo_bits}" if lo else "") + ".")
        body.append("")
        s = c["sig_row"]
        s_traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(s["v"], labels, 3, +1))
        body.append(f"**Signature season:** {s['season']} — {s_traits} "
                    f"(archetype: {clusters[s['c']]}).")
        body.append("")
        body.append("## Season chart")
        body.append("")
        body.append("| Season | Pos | Archetype | Leading traits (σ vs era) |")
        body.append("|---|---|---|---|")
        for r in rows:
            pos = positions[r["p"]] if positions and r.get("p", -1) >= 0 else "—"
            traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(r["v"], labels, 2, +1)) or "—"
            body.append(f"| {r['season']} | {pos} | {clusters[r['c']]} | {traits} |")
        body.append("")
        body.append("## Statistical neighbors")
        body.append("")
        body.append("Closest career shapes in the era-normalized vector space:")
        body.append("")
        for nb_name, cs in c["neighbors"]:
            body.append(f"- {wl(careers[nb_name]['slug'], nb_name)} — cosine {cs:.2f}")
        body.append("")
        hubs = [f"[[../archetypes/{slugify(a)}|{a}]]" for a in c["archetypes"][:2]]
        hubs += [f"[[../positions/{p.lower()}|{p}]]" for p in c["positions"][:2]]
        body.append("**Hubs:** " + " · ".join(hubs))
        body.append("")
        body.append(AUTO_END)
        body.append("")
        body.append(curated if curated is not None else DEFAULT_CURATED)

        text = "\n".join(fm) + "\n".join(body)
        if not text.endswith("\n"):
            text += "\n"
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.write_text(text, encoding="utf-8", newline="\n")
            n_new += int(is_new)
            n_updated += int(not is_new)

    # ---- archetype hubs ----
    for ci, cname in enumerate(clusters):
        centroid = np.mean([p["v"] for p in players if p["c"] == ci], axis=0)
        traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(centroid, labels, 4, +1))
        member_counts = Counter()
        for name in names:
            k = sum(1 for r in careers[name]["rows"] if r["c"] == ci)
            if k:
                member_counts[name] = k
        lines = [
            "---", "okf: 1", "kind: archetype", f"id: {slugify(cname)}",
            f"name: \"{cname}\"", f"player_seasons: {sum(member_counts.values())}",
            f"updated: {TODAY}", "---", "",
            f"# Archetype: {cname}", "", AUTO_BEGIN, "",
            f"**Centroid identity:** {traits}.", "",
            "## Most-charted members", "",
            "| Player | Seasons in archetype |", "|---|---|",
        ]
        for mname, k in member_counts.most_common(40):
            lines.append(f"| {wl('../players/' + careers[mname]['slug'], mname)} | {k} |")
        lines += ["", AUTO_END, "", DEFAULT_CURATED]
        (KNOW / "archetypes" / (slugify(cname) + ".md")).write_text(
            "\n".join(lines), encoding="utf-8", newline="\n")

    # ---- position hubs ----
    pos_full = {"PG": "Point guard", "SG": "Shooting guard", "SF": "Small forward",
                "PF": "Power forward", "C": "Center"}
    for pi, pos in enumerate(positions):
        member_counts = Counter()
        for name in names:
            k = sum(1 for r in careers[name]["rows"] if r.get("p", -1) == pi)
            if k:
                member_counts[name] = k
        lines = [
            "---", "okf: 1", "kind: position", f"id: {pos.lower()}",
            f"name: \"{pos_full.get(pos, pos)}\"",
            f"player_seasons: {sum(member_counts.values())}",
            f"updated: {TODAY}", "---", "",
            f"# Position: {pos} — {pos_full.get(pos, pos)}", "", AUTO_BEGIN, "",
            "Positions are per season, as listed by Basketball-Reference.", "",
            "## Most-charted players", "",
            "| Player | Seasons at " + pos + " |", "|---|---|",
        ]
        for mname, k in member_counts.most_common(40):
            lines.append(f"| {wl('../players/' + careers[mname]['slug'], mname)} | {k} |")
        lines += ["", AUTO_END, "", DEFAULT_CURATED]
        (KNOW / "positions" / (pos.lower() + ".md")).write_text(
            "\n".join(lines), encoding="utf-8", newline="\n")

    # ---- index ----
    ambiguous = sorted(n for n in names if careers[n]["ambiguous"])
    idx = [
        "---", "okf: 1", "kind: index", f"players: {len(names)}",
        f"player_seasons: {len(players)}",
        f"span: {data['seasons'][0]} – {data['seasons'][-1]}",
        f"updated: {TODAY}", "---", "",
        "# OKF LLM-Wiki — every charted NBA player, " +
        f"{data['seasons'][0]} to {data['seasons'][-1]}", "",
        f"{len(names)} player pages · {len(players)} player-seasons · "
        f"{len(clusters)} archetype hubs · {len(positions)} position hubs.", "",
        "- Format contract: [[OKF|OKF.md]]",
        "- Player pages: `players/<slug>.md` (slug rule shared with the game's reveal links)",
        "- Hubs: `archetypes/`, `positions/`", "",
        "## Ambiguous pages (same name, overlapping seasons — likely two people)", "",
    ]
    idx += [f"- {wl('players/' + careers[n]['slug'], n)}" for n in ambiguous] or ["- none"]
    idx.append("")
    (KNOW / "INDEX.md").write_text("\n".join(idx), encoding="utf-8", newline="\n")

    print(f"wiki: {len(names)} player pages ({n_new} new, {n_updated} refreshed), "
          f"{len(clusters)} archetype hubs, {len(positions)} position hubs, "
          f"{len(ambiguous)} flagged ambiguous")


if __name__ == "__main__":
    main()
