"""Build/refresh the OKF (Open Knowledge Format) LLM-Wiki under knowledge/.

One interlinked, machine-editable markdown page per NBA player in the
dataset (1996-97 onward), plus archetype and position hub pages and an
index. Pages are two-layer:

  - AUTO layer  — between okf:auto markers; regenerated from
    assets/vectors.json on every run. Never edit by hand.
  - CURATED layer — everything below the end marker; preserved verbatim
    across regenerations. Humans and LLM agents extend pages here.

Idempotent: re-running refreshes the auto layer and index/hubs, touching
nothing curated. See knowledge/OKF.md for the format contract.

Run:  python pipeline/build_wiki.py
"""
from __future__ import annotations

import datetime
import json
import re
import time
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
VECTORS = ROOT / "assets" / "vectors.json"
DRIFT = ROOT / "assets" / "drift.json"
KNOW = ROOT / "knowledge"
CACHE = ROOT / "pipeline" / "cache"

AUTO_BEGIN = "<!-- okf:auto:begin — regenerated by pipeline/build_wiki.py; do not edit this block -->"
AUTO_END = "<!-- okf:auto:end — curated layer below; humans and LLM agents extend the page here -->"

TODAY = datetime.date.today().isoformat()
NEIGHBORS = 6


def slugify(name: str) -> str:
    """Must match playerSlug() in assets/game.js."""
    s = unicodedata.normalize("NFD", name)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def sig(z: float) -> str:
    return ("+" if z >= 0 else "−") + f"{abs(z):.1f}σ"


def top_traits(v, labels, n=3, sign=1):
    order = sorted(range(len(v)), key=lambda i: -sign * v[i])
    return [(labels[i], v[i]) for i in order[:n] if sign * v[i] > 0]


def wl(slug: str, name: str) -> str:
    return f"[[{slug}|{name}]]"


def decade_of(season: str) -> int:
    """1999-00 -> 1990, 2000-01 -> 2000, ... — the season's starting year,
    floored to the decade, used to define "other-decade" for era twins."""
    return int(season[:4]) // 10 * 10


def root_frame_vector(v, season: str, chain_np: dict) -> np.ndarray:
    """Map a season-space vector into the 1996-97 root frame using the
    chained Procrustes transform from assets/drift.json.

    Orientation check (see pipeline/procrustes_drift.py): each pair solves
    Q minimizing ||X_new Q - Y_old||, i.e. v_old ~= v_new @ Q, and the
    chain is accumulated as `chained = chained @ Q.T`. For 1-D vectors,
    `M @ v` and `v @ M.T` are the same computation (both contract on the
    shared index), so the root-frame vector is simply chain[season] @ v
    -- verified numerically against direct re-derivation of Q from
    vectors.json for both a single pair and a 3-step chain.
    """
    M = chain_np.get(season)
    if M is None:
        return np.array(v, float)
    return M @ np.array(v, float)


# ---------------------------------------------------------------------------
# Scouting report — deterministic phrasing banks + raw-line fetcher.
# ---------------------------------------------------------------------------

POS_GROUP = {"PG": "guard", "SG": "guard", "SF": "wing", "PF": "big", "C": "big"}

STYLE_PHRASES = {
    "arc": {
        "guard": "Plays as a movement shooter: lives beyond the arc, spaces the floor from deep.",
        "wing": "Plays as a stretch wing: lives beyond the arc, opens driving lanes for others.",
        "big": "Plays as a stretch big: lives beyond the arc, unusual range for the position.",
    },
    "rim": {
        "guard": "Plays as a downhill guard: lives at the free-throw line, pressures the rim off the dribble.",
        "wing": "Plays as a slashing wing: lives at the free-throw line, attacks closeouts.",
        "big": "Plays as a rim-pressure big: lives at the line, never shoots threes.",
    },
    "balance": {
        "guard": "Plays as a balanced-diet guard: even mix of rim, midrange, and three-point shots.",
        "wing": "Plays as a balanced-diet wing: no single shot zone dominates his shot chart.",
        "big": "Plays as a balanced-diet big: works face-up and back-to-the-basket without over-relying on one look.",
    },
}

# Strength phrases: rendered as "{phrase} ({sigma} vs era)" — no "era" in the
# clause itself, so the suffix doesn't repeat the word.
STRENGTH_PHRASES = {
    "PTS": "Featured, high-usage scoring role",
    "AST": "High-volume table-setter",
    "OREB": "Relentless on the offensive glass",
    "DREB": "Strong presence on the defensive glass",
    "STL": "Active hands, disrupts passing lanes",
    "BLK": "Elite rim protection",
    "TOV": "Rarely turns the ball over",
    "FG3A": "High-volume three-point shooter",
    "FGA": "Heavy shot volume, focal scoring option",
    "FTA": "Draws contact, gets to the line often",
    "FG3_PCT": "Knockdown three-point shooter",
    "FG_PCT": "Efficient finisher inside the arc",
    "FT_PCT": "Reliable touch from the free-throw line",
    "PLUS_MINUS": "Strong net on-court impact",
}

# Concern phrases: rendered as "{phrase} ({sigma})" — "era" lives in the
# clause already, so the suffix stays bare.
CONCERN_PHRASES = {
    "PTS": "Scoring load well below era",
    "AST": "Table-setting role well below era",
    "OREB": "Offensive-glass activity well below era",
    "DREB": "Defensive rebounding well below era",
    "STL": "Ball-hawking activity well below era",
    "BLK": "Rim-protection impact well below era",
    "TOV": "Turnover rate well above era",
    "FG3A": "Three-point volume well below era",
    "FGA": "Shot volume well below era",
    "FTA": "Rim pressure (free-throw generation) well below era",
    "FG3_PCT": "Three-point accuracy well below era",
    "FG_PCT": "Finishing efficiency well below era",
    "FT_PCT": "Free-throw touch well below era",
    "PLUS_MINUS": "On-court net impact well below era",
}

INVERT_GOODNESS = {"TOV"}  # lower TOV z is the "good" direction


def style_for(v, features, pos_group: str) -> str:
    """Deterministic style sentence keyed to which of arc volume (FG3A),
    rim pressure (FTA), or midrange/balance (neither dominates) wins the
    signature season's shot-mix sigmas."""
    i3, ift, ifg = features.index("FG3A"), features.index("FTA"), features.index("FGA")
    z3, zft, zfg = v[i3], v[ift], v[ifg]
    spread = max(z3, zft, zfg) - min(z3, zft, zfg)
    if spread < 0.6:
        dom = "balance"
    elif z3 >= zft and z3 >= zfg:
        dom = "arc"
    elif zft >= z3 and zft >= zfg:
        dom = "rim"
    else:
        dom = "balance"
    return STYLE_PHRASES[dom][pos_group]


def _goodness(v, features, invert):
    idx = {f: i for i, f in enumerate(features)}
    g = list(v)
    for f in invert:
        g[idx[f]] = -v[idx[f]]
    return g


def pick_strengths(v, features, n=3, threshold=1.0):
    g = _goodness(v, features, INVERT_GOODNESS)
    order = sorted(range(len(features)), key=lambda i: -g[i])
    out = []
    for i in order:
        if g[i] < threshold:
            break
        f = features[i]
        out.append(f"{STRENGTH_PHRASES[f]} ({sig(v[i])} vs era)")
    return out[:n]


def pick_concerns(v, features, n=2, threshold=-1.0):
    g = _goodness(v, features, INVERT_GOODNESS)
    order = sorted(range(len(features)), key=lambda i: g[i])
    out = []
    for i in order:
        if g[i] > threshold:
            break
        f = features[i]
        out.append(f"{CONCERN_PHRASES[f]} ({sig(v[i])})")
    return out[:n]


def season_abbrev(season: str) -> str:
    return "'" + season.split("-")[1]


def career_shape_line(c, clusters) -> str:
    rows = c["rows"]
    n = len(rows)
    span = (rows[0]["season"] if n == 1
            else f"{rows[0]['season']}–{rows[-1]['season']}")
    plural = "season" if n == 1 else "seasons"
    first_arch = clusters[rows[0]["c"]]
    peak_arch = clusters[c["sig_row"]["c"]]
    if first_arch != peak_arch:
        return (f"Charted {n} {plural} ({span}). Entered as a {first_arch} "
                f"profile, peaked as a {peak_arch} identity.")
    return f"Charted {n} {plural} ({span}). Consistent {first_arch} profile across his career."


BASE_WANTED = ["PTS", "AST", "OREB", "DREB", "STL", "BLK", "TOV"]


def fetch_base_stats(season: str) -> dict[str, dict] | None:
    """Per-100-possession Base box stats for a season, keyed by player name.
    Cached under pipeline/cache/base_<season>.json (resumable, matches the
    caching convention in build_vectors.py). Returns None only if there is
    no cache AND every network attempt failed -- callers degrade to
    sigma-only honestly in that case."""
    path = CACHE / f"base_{season}.json"
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            pass
    try:
        from nba_api.stats.endpoints import leaguedashplayerstats
    except ImportError:
        print(f"  base stats {season}: nba_api not installed -- skipping fetch")
        return None

    for attempt in range(3):  # 1 try + 2 retries
        try:
            r = leaguedashplayerstats.LeagueDashPlayerStats(
                season=season, per_mode_detailed="Per100Possessions",
                measure_type_detailed_defense="Base", timeout=45)
            df = r.get_data_frames()[0]
            out: dict[str, dict] = {}
            for _, row in df.iterrows():
                name = str(row["PLAYER_NAME"])
                out[name] = {
                    k: (None if row.get(k) is None else float(row[k]))
                    for k in BASE_WANTED if k in df.columns
                }
            CACHE.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(out), encoding="utf-8")
            time.sleep(0.8)
            return out
        except Exception as e:
            print(f"  base stats {season}: attempt {attempt + 1}/3 failed "
                  f"({type(e).__name__})")
            time.sleep(0.8)
    print(f"  base stats {season}: EXHAUSTED retries -- degrading to sigma-only")
    return None


def split_curated(path: Path) -> str | None:
    """Return the curated tail of an existing page, or None."""
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    idx = text.find(AUTO_END)
    if idx < 0:
        return None
    return text[idx + len(AUTO_END):].lstrip("\n")


DEFAULT_CURATED = """## Notes

<!-- Curated layer. Add scouting notes, history, film observations,
     corrections, and further [[wikilinks]] here. The generator never
     touches anything below the auto end marker. -->
"""


def main() -> None:
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    labels = [data["featureLabels"][f] for f in data["features"]]
    clusters = data["clusters"]
    positions = data.get("positions", [])
    players = data["players"]

    # ---- group player-seasons by name (the dataset carries no person id;
    #      same-name players are flagged, see `ambiguous`) ----
    by_name: dict[str, list[dict]] = defaultdict(list)
    for p in players:
        by_name[p["name"]].append(p)

    careers = {}
    for name, rows in by_name.items():
        rows.sort(key=lambda r: r["season"])
        seasons = [r["season"] for r in rows]
        ambiguous = len(seasons) != len(set(seasons))
        mean_v = np.mean([r["v"] for r in rows], axis=0)
        # signature season: the most extreme statistical identity
        sig_row = max(rows, key=lambda r: float(np.linalg.norm(r["v"])))
        pos_seen = [positions[r["p"]] for r in rows if positions and r.get("p", -1) >= 0]
        arch_seen = [clusters[r["c"]] for r in rows]
        careers[name] = {
            "slug": slugify(name),
            "rows": rows,
            "mean_v": mean_v,
            "sig_row": sig_row,
            "positions": [p for p, _ in Counter(pos_seen).most_common()],
            "archetypes": [a for a, _ in Counter(arch_seen).most_common()],
            "ambiguous": ambiguous,
        }

    # slug collisions across *different* names (extremely rare) -> suffix
    used: dict[str, str] = {}
    for name, c in sorted(careers.items()):
        if c["slug"] in used and used[c["slug"]] != name:
            c["slug"] = c["slug"] + "-" + slugify(c["rows"][0]["season"])
        used[c["slug"]] = name

    # ---- nearest statistical neighbors on career-mean vectors ----
    names = sorted(careers)
    M = np.array([careers[n]["mean_v"] for n in names])
    Mn = M / np.maximum(np.linalg.norm(M, axis=1, keepdims=True), 1e-9)
    S = Mn @ Mn.T
    np.fill_diagonal(S, -2)
    for i, n in enumerate(names):
        idxs = np.argsort(-S[i])[:NEIGHBORS]
        careers[n]["neighbors"] = [(names[j], float(S[i, j])) for j in idxs]

    # ---- era twins: nearest OTHER-DECADE player, in the root (1996-97)
    #      Procrustes frame, on signature-season vectors ----
    if DRIFT.exists():
        drift = json.loads(DRIFT.read_text(encoding="utf-8"))
        chain_np = {season: np.array(mat, float) for season, mat in drift["chainedToRoot"].items()}
        decades = np.array([decade_of(careers[n]["sig_row"]["season"]) for n in names])
        ERA = np.stack([
            root_frame_vector(careers[n]["sig_row"]["v"], careers[n]["sig_row"]["season"], chain_np)
            for n in names
        ])
        ERAn = ERA / np.maximum(np.linalg.norm(ERA, axis=1, keepdims=True), 1e-9)
        ES = ERAn @ ERAn.T
        for i, n in enumerate(names):
            other_decade = decades != decades[i]
            if not other_decade.any():
                careers[n]["era_twin"] = None
                continue
            masked = np.where(other_decade, ES[i], -2.0)
            j = int(np.argmax(masked))
            careers[n]["era_twin"] = (names[j], careers[names[j]]["sig_row"]["season"], float(ES[i, j]))
    else:
        for n in names:
            careers[n]["era_twin"] = None

    # ---- scouting reports: raw per-100 stat line for each signature season,
    #      fetched/cached per season (pipeline/cache/base_<season>.json) ----
    needed_seasons = sorted({c["sig_row"]["season"] for c in careers.values()})
    base_cache: dict[str, dict | None] = {}
    fetched_ok = 0
    for season in needed_seasons:
        base_cache[season] = fetch_base_stats(season)
        if base_cache[season] is not None:
            fetched_ok += 1
    print(f"scouting raw lines: {fetched_ok}/{len(needed_seasons)} signature "
          f"seasons available (cached or fetched)")

    (KNOW / "players").mkdir(parents=True, exist_ok=True)
    (KNOW / "archetypes").mkdir(exist_ok=True)
    (KNOW / "positions").mkdir(exist_ok=True)

    # ---- player pages ----
    n_new = n_updated = 0
    for name in names:
        c = careers[name]
        rows = c["rows"]
        path = KNOW / "players" / (c["slug"] + ".md")
        curated = split_curated(path)
        is_new = curated is None

        hi = top_traits(c["mean_v"], labels, 3, +1)
        lo = top_traits(-c["mean_v"], labels, 2, +1)
        span = f"{rows[0]['season']} – {rows[-1]['season']}"

        fm = [
            "---",
            "okf: 1",
            "kind: player",
            f"id: {c['slug']}",
            f"name: \"{name}\"",
            f"seasons_charted: {len(rows)}",
            f"span: {span}",
            f"positions: [{', '.join(c['positions']) or 'unlisted'}]",
            f"archetypes: [{'; '.join(c['archetypes'][:2])}]",
        ]
        if c["ambiguous"]:
            fm.append("ambiguous: true  # duplicate name+season rows — likely two different players share this name")
        fm += [f"updated: {TODAY}", "---"]

        body = ["", f"# {name}", "", AUTO_BEGIN, ""]
        id_bits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in hi)
        lo_bits = " · ".join(f"{lbl} {sig(z * -1)}" for lbl, z in lo)
        body.append(f"**Vector identity (career mean vs era):** {id_bits}" +
                    (f" — thin: {lo_bits}" if lo else "") + ".")
        body.append("")
        s = c["sig_row"]
        s_traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(s["v"], labels, 3, +1))
        body.append(f"**Signature season:** {s['season']} — {s_traits} "
                    f"(archetype: {clusters[s['c']]}).")
        body.append("")
        body.append("## Season chart")
        body.append("")
        body.append("| Season | Pos | Archetype | Leading traits (σ vs era) |")
        body.append("|---|---|---|---|")
        for r in rows:
            pos = positions[r["p"]] if positions and r.get("p", -1) >= 0 else "—"
            traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(r["v"], labels, 2, +1)) or "—"
            body.append(f"| {r['season']} | {pos} | {clusters[r['c']]} | {traits} |")
        body.append("")
        body.append("## Statistical neighbors")
        body.append("")
        body.append("Closest career shapes in the era-normalized vector space:")
        body.append("")
        for nb_name, cs in c["neighbors"]:
            body.append(f"- {wl(careers[nb_name]['slug'], nb_name)} — cosine {cs:.2f}")
        body.append("")

        body.append("## Scouting report")
        body.append("")
        sig_pos_idx = s.get("p", -1)
        sig_pos = positions[sig_pos_idx] if positions and sig_pos_idx is not None and sig_pos_idx >= 0 else None
        pos_label = sig_pos or (c["positions"][0] if c["positions"] else "Unlisted")
        pos_group = POS_GROUP.get(pos_label, "wing")
        style_sentence = style_for(s["v"], data["features"], pos_group)
        body.append(f"**Play style:** {pos_label} · {clusters[s['c']]}. {style_sentence}")
        body.append("")
        raw_rows = base_cache.get(s["season"])
        raw = raw_rows.get(name) if raw_rows else None
        if raw and raw.get("PTS") is not None and raw.get("AST") is not None:
            reb = (raw.get("OREB") or 0.0) + (raw.get("DREB") or 0.0)
            stl_v, blk_v = raw.get("STL") or 0.0, raw.get("BLK") or 0.0
            stat4_label, stat4_val = ("blk", blk_v) if blk_v > stl_v else ("stl", stl_v)
            raw_line = (f"{raw['PTS']:.1f} pts · {reb:.1f} reb · {raw['AST']:.1f} ast · "
                        f"{stat4_val:.1f} {stat4_label} per 100 ({s['season']})")
            body.append(f"**Signature-season stat line:** {raw_line}.")
        else:
            body.append(f"**Signature-season stat line:** (era-relative profile; raw line "
                        f"pending refetch) — {s['season']}.")
        body.append("")
        body.append("**Strengths:**")
        body.append("")
        strengths = pick_strengths(s["v"], data["features"])
        if strengths:
            for line in strengths:
                body.append(f"- {line}")
        else:
            body.append("- No standout statistical trait clears +1.0σ at his peak.")
        body.append("")
        body.append("**Areas of concern:**")
        body.append("")
        concerns = pick_concerns(s["v"], data["features"])
        if concerns:
            for line in concerns:
                body.append(f"- {line}")
        else:
            body.append("- No glaring statistical weakness at his peak.")
        body.append("")
        body.append("**Comparables:**")
        body.append("")
        for nb_name, cs2 in c["neighbors"]:
            nb_season = careers[nb_name]["sig_row"]["season"]
            pct = round(max(0.0, cs2) * 100)
            body.append(f"- {wl(careers[nb_name]['slug'], nb_name)} "
                        f"{season_abbrev(nb_season)} ({pct}% similar)")
        body.append("")
        body.append(f"**Career shape:** {career_shape_line(c, clusters)}")
        body.append("")
        twin = c.get("era_twin")
        if twin:
            twin_name, twin_season, twin_cos = twin
            twin_pct = round(max(0.0, twin_cos) * 100)
            body.append(f"**Era twin:** {wl(careers[twin_name]['slug'], twin_name)} "
                        f"{season_abbrev(twin_season)} ({twin_pct}% aligned similarity — "
                        f"cross-era via Procrustes chaining).")
            body.append("")

        hubs = [f"[[../archetypes/{slugify(a)}|{a}]]" for a in c["archetypes"][:2]]
        hubs += [f"[[../positions/{p.lower()}|{p}]]" for p in c["positions"][:2]]
        body.append("**Hubs:** " + " · ".join(hubs))
        body.append("")
        body.append(AUTO_END)
        body.append("")
        body.append(curated if curated is not None else DEFAULT_CURATED)

        text = "\n".join(fm) + "\n".join(body)
        if not text.endswith("\n"):
            text += "\n"
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.write_text(text, encoding="utf-8", newline="\n")
            n_new += int(is_new)
            n_updated += int(not is_new)

    # ---- archetype hubs ----
    for ci, cname in enumerate(clusters):
        centroid = np.mean([p["v"] for p in players if p["c"] == ci], axis=0)
        traits = " · ".join(f"{lbl} {sig(z)}" for lbl, z in top_traits(centroid, labels, 4, +1))
        member_counts = Counter()
        for name in names:
            k = sum(1 for r in careers[name]["rows"] if r["c"] == ci)
            if k:
                member_counts[name] = k
        lines = [
            "---", "okf: 1", "kind: archetype", f"id: {slugify(cname)}",
            f"name: \"{cname}\"", f"player_seasons: {sum(member_counts.values())}",
            f"updated: {TODAY}", "---", "",
            f"# Archetype: {cname}", "", AUTO_BEGIN, "",
            f"**Centroid identity:** {traits}.", "",
            "## Most-charted members", "",
            "| Player | Seasons in archetype |", "|---|---|",
        ]
        for mname, k in member_counts.most_common(40):
            lines.append(f"| {wl('../players/' + careers[mname]['slug'], mname)} | {k} |")
        lines += ["", AUTO_END, "", DEFAULT_CURATED]
        (KNOW / "archetypes" / (slugify(cname) + ".md")).write_text(
            "\n".join(lines), encoding="utf-8", newline="\n")

    # ---- position hubs ----
    pos_full = {"PG": "Point guard", "SG": "Shooting guard", "SF": "Small forward",
                "PF": "Power forward", "C": "Center"}
    for pi, pos in enumerate(positions):
        member_counts = Counter()
        for name in names:
            k = sum(1 for r in careers[name]["rows"] if r.get("p", -1) == pi)
            if k:
                member_counts[name] = k
        lines = [
            "---", "okf: 1", "kind: position", f"id: {pos.lower()}",
            f"name: \"{pos_full.get(pos, pos)}\"",
            f"player_seasons: {sum(member_counts.values())}",
            f"updated: {TODAY}", "---", "",
            f"# Position: {pos} — {pos_full.get(pos, pos)}", "", AUTO_BEGIN, "",
            "Positions are per season, as listed by Basketball-Reference.", "",
            "## Most-charted players", "",
            "| Player | Seasons at " + pos + " |", "|---|---|",
        ]
        for mname, k in member_counts.most_common(40):
            lines.append(f"| {wl('../players/' + careers[mname]['slug'], mname)} | {k} |")
        lines += ["", AUTO_END, "", DEFAULT_CURATED]
        (KNOW / "positions" / (pos.lower() + ".md")).write_text(
            "\n".join(lines), encoding="utf-8", newline="\n")

    # ---- index ----
    ambiguous = sorted(n for n in names if careers[n]["ambiguous"])
    idx = [
        "---", "okf: 1", "kind: index", f"players: {len(names)}",
        f"player_seasons: {len(players)}",
        f"span: {data['seasons'][0]} – {data['seasons'][-1]}",
        f"updated: {TODAY}", "---", "",
        "# OKF LLM-Wiki — every charted NBA player, " +
        f"{data['seasons'][0]} to {data['seasons'][-1]}", "",
        f"{len(names)} player pages · {len(players)} player-seasons · "
        f"{len(clusters)} archetype hubs · {len(positions)} position hubs.", "",
        "- Format contract: [[OKF|OKF.md]]",
        "- Player pages: `players/<slug>.md` (slug rule shared with the game's reveal links)",
        "- Hubs: `archetypes/`, `positions/`", "",
        "## Ambiguous pages (same name, overlapping seasons — likely two people)", "",
    ]
    idx += [f"- {wl('players/' + careers[n]['slug'], n)}" for n in ambiguous] or ["- none"]
    idx.append("")
    (KNOW / "INDEX.md").write_text("\n".join(idx), encoding="utf-8", newline="\n")

    print(f"wiki: {len(names)} player pages ({n_new} new, {n_updated} refreshed), "
          f"{len(clusters)} archetype hubs, {len(positions)} position hubs, "
          f"{len(ambiguous)} flagged ambiguous")


if __name__ == "__main__":
    main()
