#!/usr/bin/env bash
# Operator runbook — activate the Pedigree tower (Track H).
#
# Run this ONCE on a machine that can reach stats.nba.com (a home/office
# IP — datacenter/CI IPs are blocked). It fetches the full NBA draft
# history in a single API call, rebuilds the pedigree features against the
# real cache, runs the full-coverage gates, and then STOPS and shows you
# the exact commit command so you can review before committing.
#
# The only artifact that gets committed is pipeline/cache/draft_history.json
# (pipeline/data/ is gitignored and regenerated by the growth loop / MTNN).
#
#   bash pipeline/operator_fetch_pedigree.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root regardless of where it's invoked

PY="${PYTHON:-python3}"

echo "== 1/4  dependencies"
if ! "$PY" -c "import curl_cffi" 2>/dev/null; then
  echo "   curl_cffi not found — installing (Akamai TLS bypass for stats.nba.com)"
  "$PY" -m pip install --quiet curl_cffi
else
  echo "   curl_cffi present"
fi
if ! "$PY" -c "import nba_api" 2>/dev/null; then
  echo "   nba_api not found — installing nba_api + numpy"
  "$PY" -m pip install --quiet nba_api numpy
else
  echo "   nba_api present"
fi

echo "== 2/4  fetch full draft history (one stats.nba.com call)"
# On a 429/block the fetcher backs off and retries; if it ultimately fails
# it exits non-zero and this script stops (set -e) — just re-run later.
"$PY" pipeline/fetch_draft_history.py

echo "== 3/4  rebuild pedigree from the REAL cache + run gates"
"$PY" pipeline/build_pedigree.py           # no --fixture: uses draft_history.json
"$PY" pipeline/test_pedigree.py            # detects real cache -> full-coverage gates

echo "== 4/4  review + commit"
echo
git --no-pager diff --stat -- pipeline/cache/draft_history.json || true
echo
cat <<'NEXT'
Draft history fetched and all pedigree gates passed against real coverage.

To ship it (review the cache first, then run):

    git add pipeline/cache/draft_history.json
    git commit -m "Activate Pedigree tower: full NBA draft history cache"
    git push

That lands on PR #1 and lights up the pedigree family for ~all players.
The weekly refresh (update_dataset.py) will keep it current from here.

Optional — regenerate MTNN metrics with real pedigree coverage:

    python pipeline/bootstrap_train_matrix.py
    python pipeline/build_pedigree.py
    python pipeline/integrate_context.py
    python pipeline/train_mtnn.py --epochs 40
    # -> pipeline/data/mtnn_report.json  (pedigree_expectation R2/MAE, full coverage)
NEXT
