#!/usr/bin/env bash
# Operator runbook — activate the Playoffs track (Track I).
#
# Run on a machine that can reach stats.nba.com (a home/office IP —
# datacenter/CI IPs are blocked). It fetches playoff + regular-season
# splits and team playoff records for every charted season, rebuilds the
# `playoffs` family against real coverage, writes the transparent
# assets/playoffs.json for the game's Playoff Lens, runs the full gates,
# then STOPS and prints the exact commit command so you can review first.
#
# Committed artifacts: pipeline/cache/playoffs_*.json (source caches) and
# assets/playoffs.json (transparent splits the live game reads).
# pipeline/data/ is gitignored and regenerated by the growth loop / MTNN.
#
#   bash pipeline/operator_fetch_playoffs.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

PY="${PYTHON:-python3}"

echo "== 1/5  dependencies"
if ! "$PY" -c "import nba_api" 2>/dev/null; then
  echo "   installing nba_api + numpy"
  "$PY" -m pip install --quiet nba_api numpy
else
  echo "   nba_api present"
fi

echo "== 2/5  fetch playoff + regular-season splits (resumes from cache)"
# Two GETs/season + one team pull; on a 429 the fetcher backs off and
# retries, then exits non-zero (set -e stops us) — just re-run to resume.
"$PY" pipeline/fetch_playoffs.py
"$PY" pipeline/repair_playoff_rounds.py   # era-aware 15-win champions → rounds=4

echo "== 3/5  fetch playoff game logs + series matchups"
"$PY" pipeline/fetch_playoff_gamelogs.py

echo "== 4/5  rebuild playoffs family + transparent asset + gates"
"$PY" pipeline/build_playoffs.py          # real caches -> writes assets/playoffs.json
"$PY" pipeline/test_playoffs.py           # detects real caches -> full-coverage gates

echo "== 5/5  review + commit"
echo
git --no-pager diff --stat -- assets/playoffs.json assets/playoff_paths.json pipeline/cache/ || true
echo
cat <<'NEXT'
Playoff splits + game logs fetched and all gates passed against real coverage.

To ship it (review, then run):

    git add pipeline/cache/playoffs_*.json pipeline/cache/playoff_games_*.json \
            assets/playoffs.json assets/playoff_paths.json
    git commit -m "Playoffs: series matchups + game logs; fix pre-2003 champion rounds"
    git push

That lands: Skills Lens shows series path + expandable game log, and the
MTNN playoffs tower gains PO_SERIES / close-game / scoring features.
NEXT
