#!/usr/bin/env bash
# Operator runbook — activate wide-matrix skills (Track J: post/transition/motor).
#
# Run on a machine that can reach stats.nba.com (a home/office IP —
# datacenter/CI IPs are blocked). Fetches synergy play-types + hustle
# stats for the tracked seasons (2015-16+), rebuilds the three masked
# skills, writes the transparent assets/skills_wide.json the Skills Lens
# reads, runs the gates, then STOPS and prints the commit command.
#
# Committed artifacts: pipeline/cache/wide_skills_*.json + assets/skills_wide.json.
# pipeline/data/ is gitignored and regenerated by the growth loop / MTNN.
#
#   bash pipeline/operator_fetch_wide_skills.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."
PY="${PYTHON:-python3}"

echo "== 1/4  dependencies"
if ! "$PY" -c "import curl_cffi" 2>/dev/null; then
  echo "   installing curl_cffi (Akamai bypass for stats.nba.com)"
  "$PY" -m pip install --quiet curl_cffi
else
  echo "   curl_cffi present"
fi

echo "== 2/4  fetch synergy + hustle + tracking (2015-16+, resumes from cache)"
"$PY" pipeline/fetch_wide_skills.py

echo "== 3/4  rebuild wide skills + transparent asset + gates"
"$PY" pipeline/build_wide_skills.py       # real caches -> writes assets/skills_wide.json
"$PY" pipeline/test_wide_skills.py

echo "== 4/4  review + commit"
echo
git --no-pager diff --stat -- assets/skills_wide.json pipeline/cache/ || true
echo
cat <<'NEXT'
Wide skills fetched and all gates passed against real coverage.

To ship it (review, then run):

    git add pipeline/cache/wide_skills_*.json assets/skills_wide.json
    git commit -m "Activate wide skills: post / transition / motor (2015-16+)"
    git push

The Skills Lens then shows Post / Transition / Motor / Shooting Gravity /
Rim Gravity bars from 2015-16 on (earlier seasons stay "not tracked").
The MTNN skill towers pick up the five masked targets on the next retrain.
NEXT
