#!/usr/bin/env bash
# Operator runbook — activate the Playoffs track (Track I).
#
# Run on a machine that can reach stats.nba.com (a home/office IP —
# datacenter/CI IPs are blocked). It fetches playoff + regular-season
# splits and team playoff records for every charted season, rebuilds the
# `playoffs` family against real coverage, writes the transparent
# assets/playoffs.json for the game's Playoff Lens, runs the full gates,
# then STOPS and prints the exact commit command so you can review first.
#
# Committed artifacts: pipeline/cache/playoffs_*.json (source caches) and
# assets/playoffs.json (transparent splits the live game reads).
# pipeline/data/ is gitignored and regenerated by the growth loop / MTNN.
#
#   bash pipeline/operator_fetch_playoffs.sh
#
set -euo pipefail
cd "$(dirname "$0")/.."

PY="${PYTHON:-python3}"

echo "== 1/4  dependencies"
if ! "$PY" -c "import nba_api" 2>/dev/null; then
  echo "   installing nba_api + numpy"
  "$PY" -m pip install --quiet nba_api numpy
else
  echo "   nba_api present"
fi

echo "== 2/4  fetch playoff + regular-season splits (resumes from cache)"
# Two GETs/season + one team pull; on a 429 the fetcher backs off and
# retries, then exits non-zero (set -e stops us) — just re-run to resume.
"$PY" pipeline/fetch_playoffs.py

echo "== 3/4  rebuild playoffs family + transparent asset + gates"
"$PY" pipeline/build_playoffs.py          # real caches -> writes assets/playoffs.json
"$PY" pipeline/test_playoffs.py           # detects real caches -> full-coverage gates

echo "== 4/4  review + commit"
echo
git --no-pager diff --stat -- assets/playoffs.json pipeline/cache/ || true
echo
cat <<'NEXT'
Playoff splits fetched and all gates passed against real coverage.

To ship it (review, then run):

    git add pipeline/cache/playoffs_*.json assets/playoffs.json
    git commit -m "Activate Playoffs track: postseason splits + game Playoff Lens"
    git push

That lands on PR #1: the live Skills Lens shows regular-season vs playoff
splits + riser/fader, and the MTNN playoffs tower gains real coverage.
The weekly refresh (update_dataset.py) keeps it current after each postseason.

Optional — regenerate MTNN metrics with real playoff coverage:

    python pipeline/bootstrap_train_matrix.py
    python pipeline/build_pedigree.py   # if you also activated Track H
    python pipeline/build_playoffs.py
    python pipeline/integrate_context.py
    python pipeline/train_mtnn.py --epochs 40
    # -> mtnn_report.json: playoff_riser R2/MAE on real held-out seasons
NEXT
