"""Wide sources may contribute their declared columns, and nothing else.

A fourth instance of the class test_feature_hygiene.py was written for: a change
that breaks no build and moves no loss curve, and quietly degrades the model.

pipeline/cache/bio_*.json gained ten undeclared keys from the combine scaffolds.
Two are strings and crash `float(v)` in build_vectors' matrix assembly -- loud,
and how this was found. The other eight are silent and worse: wingspan_in,
standing_reach_in, vertical_max_in and friends are *synthetic*, generated by
fetch_combine.py:154 ("inches + 4.5 + deterministic jitter") and
fetch_missing_combine.py:9 ("height*1.07 + pos_adj + bounded_noise"). Copied
into the matrix they would widen the bio tower from 4 columns to 11 with
fabricated measurements, and per audit_features.py a family's width is its
fusion share -- so bio would gain pull on the strength of noise.

The shipped 142-feature matrix predates those cache keys, so no shipped model
ever saw them. This gate is what keeps that true through the next rebuild.

Run:  python -m pytest pipeline/test_source_contracts.py -q
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "pipeline" / "data"
CACHE = ROOT / "pipeline" / "cache"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_vectors import (  # noqa: E402
    BIO_COLS,
    SOURCE_CONTRACTS,
    TRACKING_SPECS,
    source_columns,
)

# Named here so a failure says which fabrication got in, not just "a key".
SYNTHETIC_BIO_KEYS = {
    "combine_method",
    "combine_source",
    "wingspan_in",
    "standing_reach_in",
    "vertical_max_in",
    "vertical_max",
    "wingspan",
    "standing_reach",
    "vertical_standing_in",
    "pos_used",
}


def _a_bio_record() -> dict | None:
    """One real cached bio record, or None if the cache isn't present."""
    for p in sorted(CACHE.glob("bio_*.json")):
        try:
            doc = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        rows = doc if isinstance(doc, list) else list(doc.values())
        if rows and isinstance(rows[0], dict):
            return rows[0]
    return None


def test_bio_contract_is_exactly_bio_cols():
    assert SOURCE_CONTRACTS["bio"] == frozenset(BIO_COLS)


def test_undeclared_keys_are_dropped():
    """The filter drops anything outside the contract -- strings and floats alike."""
    record = {
        "PLAYER_ID": 243,
        "PLAYER_NAME": "Aaron McKie",
        "PLAYER_HEIGHT_INCHES": 77.0,
        "PLAYER_WEIGHT": 209.0,
        "AGE": 31.0,
        "DRAFT_NUMBER": 17.0,
        "combine_method": "estimated",  # string: crashes the float cast
        "wingspan_in": 83.4,  # float: silently becomes a feature
        "vertical_max_in": 30.6,
    }
    kept = source_columns("bio", record)
    assert set(kept) == set(BIO_COLS)
    assert "wingspan_in" not in kept, "synthetic combine measurement reached the matrix"
    assert "combine_method" not in kept


def test_identity_columns_are_never_features():
    kept = source_columns("advanced", {"PLAYER_ID": 1, "PLAYER_NAME": "x", "USG_PCT": 0.2})
    assert set(kept) == {"USG_PCT"}


def test_uncontracted_sources_pass_through():
    """advanced/scoring are constrained by fetch_dash's column list, not here."""
    kept = source_columns("advanced", {"NET_RATING": 1.0, "TS_PCT": 0.5})
    assert set(kept) == {"NET_RATING", "TS_PCT"}


def test_the_guard_is_guarding_something_live():
    """If the cache stops carrying undeclared keys, this test should be revisited.

    A green suite proves nothing when the hazard has silently disappeared -- this
    asserts the bio cache really does still contain the keys being filtered, so
    the gate above is protecting a live path rather than a historical one.
    """
    record = _a_bio_record()
    if record is None:
        # bio_*.json is tracked, so this should never happen; if it does, say so
        # rather than pass with nothing asserted.
        pytest.skip("no pipeline/cache/bio_*.json record in this checkout")
    undeclared = set(record) - set(BIO_COLS) - {"PLAYER_ID", "PLAYER_NAME"}
    assert undeclared, "bio cache no longer carries undeclared keys -- re-check this gate"
    assert undeclared & SYNTHETIC_BIO_KEYS, f"unexpected undeclared bio keys: {sorted(undeclared)}"
    assert not (set(source_columns("bio", record)) - set(BIO_COLS))


def test_tracking_contract_is_tracking_specs():
    """[ingest#11] the tracking merge is held to the columns build_vectors itself fetches."""
    assert SOURCE_CONTRACTS["tracking"] == frozenset(c for _, cols in TRACKING_SPECS for c in cols)
    kept = source_columns("tracking", {"DRIVES": 5.0, "player_name": "x", "gp": 70.0, "screen_ast": 3.0})
    assert kept == {"DRIVES": 5.0}, "fetch_advanced_tracking-style raw keys must not join the tracking family"


def test_every_tracking_cache_key_is_in_the_contract():
    """The 13 tracking caches hold only contract keys, so the filter changes no column today."""
    paths = sorted(p for p in CACHE.glob("tracking_*.json") if re.fullmatch(r"tracking_\d{4}-\d{2}\.json", p.name))
    assert len(paths) >= 13, f"expected the 2013-14.. tracking caches, found {len(paths)}"
    for p in paths:
        doc = json.loads(p.read_text(encoding="utf-8"))
        keys = {k for rec in doc.values() for k in rec}
        assert keys <= SOURCE_CONTRACTS["tracking"], (
            f"{p.name}: keys outside the contract {sorted(keys - SOURCE_CONTRACTS['tracking'])}"
        )


# What fetch_wide_skills.build_season_cache writes per player. The proxy
# 2013-14/2014-15 docs (complete: false, `_proxy`/`_source` keys) were deleted
# and both readers refuse proxy docs [ingest#5]; only complete docs are held here.
WIDE_SKILL_KEYS = {
    "post_freq",
    "post_ppp",
    "trans_freq",
    "trans_ppp",
    "screen_ast",
    "deflections",
    "loose_balls",
    "charges",
    "box_outs",
    "contested_shots",
    "pull_up_fg3a",
    "d_fg_pct",
}


def test_every_complete_wide_skills_cache_key_is_declared():
    paths = sorted(
        p for p in CACHE.glob("wide_skills_*.json") if re.fullmatch(r"wide_skills_\d{4}-\d{2}\.json", p.name)
    )
    complete = 0
    for p in paths:
        doc = json.loads(p.read_text(encoding="utf-8"))
        if not doc.get("complete"):
            continue
        complete += 1
        keys = {k for rec in doc["players"].values() for k in rec}
        assert keys <= WIDE_SKILL_KEYS, f"{p.name}: undeclared keys {sorted(keys - WIDE_SKILL_KEYS)}"
    assert complete >= 11, f"expected the 2015-16.. complete wide-skill caches, found {complete}"


@pytest.mark.local_data
def test_no_synthetic_key_reached_the_shipped_manifest():
    # feature_manifest.json is gitignored. This used to `return` when it was
    # absent, so on every CI runner it reported PASS having checked nothing.
    man = DATA / "feature_manifest.json"
    if not man.exists():
        pytest.skip(f"local data missing: {man.relative_to(ROOT).as_posix()}")
    features = set(json.loads(man.read_text(encoding="utf-8"))["features"])
    leaked = features & SYNTHETIC_BIO_KEYS
    assert not leaked, f"synthetic combine columns are in the matrix: {sorted(leaked)}"
