"""Wide sources may contribute their declared columns, and nothing else.

A fourth instance of the class test_feature_hygiene.py was written for: a change
that breaks no build and moves no loss curve, and quietly degrades the model.

pipeline/cache/bio_*.json gained ten undeclared keys from the combine scaffolds.
Two are strings and crash `float(v)` in build_vectors' matrix assembly -- loud,
and how this was found. The other eight are silent and worse: wingspan_in,
standing_reach_in, vertical_max_in and friends are *synthetic*, generated by
fetch_combine.py:154 ("inches + 4.5 + deterministic jitter") and
fetch_missing_combine.py:9 ("height*1.07 + pos_adj + bounded_noise"). Copied
into the matrix they would widen the bio tower from 4 columns to 11 with
fabricated measurements, and per audit_features.py a family's width is its
fusion share -- so bio would gain pull on the strength of noise.

The shipped 142-feature matrix predates those cache keys, so no shipped model
ever saw them. This gate is what keeps that true through the next rebuild.

Run:  python -m pytest pipeline/test_source_contracts.py -q
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "pipeline" / "data"
CACHE = ROOT / "pipeline" / "cache"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_vectors import (  # noqa: E402
    BIO_COLS,
    SOURCE_CONTRACTS,
    source_columns,
)

# Named here so a failure says which fabrication got in, not just "a key".
SYNTHETIC_BIO_KEYS = {
    "combine_method",
    "combine_source",
    "wingspan_in",
    "standing_reach_in",
    "vertical_max_in",
    "vertical_max",
    "wingspan",
    "standing_reach",
    "vertical_standing_in",
    "pos_used",
}


def _a_bio_record() -> dict | None:
    """One real cached bio record, or None if the cache isn't present."""
    for p in sorted(CACHE.glob("bio_*.json")):
        try:
            doc = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        rows = doc if isinstance(doc, list) else list(doc.values())
        if rows and isinstance(rows[0], dict):
            return rows[0]
    return None


def test_bio_contract_is_exactly_bio_cols():
    assert SOURCE_CONTRACTS["bio"] == frozenset(BIO_COLS)


def test_undeclared_keys_are_dropped():
    """The filter drops anything outside the contract -- strings and floats alike."""
    record = {
        "PLAYER_ID": 243,
        "PLAYER_NAME": "Aaron McKie",
        "PLAYER_HEIGHT_INCHES": 77.0,
        "PLAYER_WEIGHT": 209.0,
        "AGE": 31.0,
        "DRAFT_NUMBER": 17.0,
        "combine_method": "estimated",  # string: crashes the float cast
        "wingspan_in": 83.4,  # float: silently becomes a feature
        "vertical_max_in": 30.6,
    }
    kept = source_columns("bio", record)
    assert set(kept) == set(BIO_COLS)
    assert "wingspan_in" not in kept, "synthetic combine measurement reached the matrix"
    assert "combine_method" not in kept


def test_identity_columns_are_never_features():
    kept = source_columns("advanced", {"PLAYER_ID": 1, "PLAYER_NAME": "x", "USG_PCT": 0.2})
    assert set(kept) == {"USG_PCT"}


def test_uncontracted_sources_pass_through():
    """advanced/scoring are constrained by fetch_dash's column list, not here."""
    kept = source_columns("advanced", {"NET_RATING": 1.0, "TS_PCT": 0.5})
    assert set(kept) == {"NET_RATING", "TS_PCT"}


def test_the_guard_is_guarding_something_live():
    """If the cache stops carrying undeclared keys, this test should be revisited.

    A green suite proves nothing when the hazard has silently disappeared -- this
    asserts the bio cache really does still contain the keys being filtered, so
    the gate above is protecting a live path rather than a historical one.
    """
    record = _a_bio_record()
    if record is None:
        return  # no cache in this checkout; nothing to assert
    undeclared = set(record) - set(BIO_COLS) - {"PLAYER_ID", "PLAYER_NAME"}
    assert undeclared, "bio cache no longer carries undeclared keys -- re-check this gate"
    assert undeclared & SYNTHETIC_BIO_KEYS, f"unexpected undeclared bio keys: {sorted(undeclared)}"
    assert not (set(source_columns("bio", record)) - set(BIO_COLS))


def test_no_synthetic_key_reached_the_shipped_manifest():
    man = DATA / "feature_manifest.json"
    if not man.exists():
        return
    features = set(json.loads(man.read_text(encoding="utf-8"))["features"])
    leaked = features & SYNTHETIC_BIO_KEYS
    assert not leaked, f"synthetic combine columns are in the matrix: {sorted(leaked)}"
