#!/usr/bin/env python3
"""Verify docs/ARCHETYPE_ERA_RESEARCH.md against the artifacts it cites.

Solo personal project, no connection to employer, built with public/free-tier only

WHY. That document was committed 2026-07-06 and its artifacts have been regenerated by
six commits since. Every load-bearing number in it had drifted, and not slightly:

    class shares      doc: stable 44.4 / migrator 24.1 / reinvention 9.4
                      artifact: 58.9 / 8.3 / 21.6          (migrator off by 3x)
    transition rate   doc: 1990s 0.369 -> 2020s 0.397, "careers migrate more now"
                      artifact: 0.141 -> 0.162, and it PEAKS in the 2010s
    archetype names   doc lists "Three-Point Accuracy (Low Turnovers)" and friends;
                      the artifact's K=8 names are completely different

The last one matters most: the doc is not describing a stale run of the same model, it is
describing a DIFFERENT MODEL. Anyone reading it for archetype vocabulary got names that
do not exist in any current asset.

A number a human maintains by hand rots. This is the same mechanism dottie uses for its
ruff figures (scripts/check_documented_counts.py) and for the HANDOFF sha
(scripts/check_handoff_fresh.py), for the same reason: a warning in the file does not
work, a failing check does.

    python scripts/check_doc_numbers.py           # report
    python scripts/check_doc_numbers.py --check   # exit 1 on any drift

DELIBERATELY NARROW. It checks figures that can be read straight out of an artifact:
class shares, career lengths, transition rates, the archetype name set, and the
player-season count. It does NOT try to verify prose claims or the separability tables —
a check that cries wolf gets ignored, and these five are the ones that were wrong.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "ARCHETYPE_ERA_RESEARCH.md"
TRAJ = ROOT / "assets" / "trajectories.json"
ARCH = ROOT / "assets" / "archetypes_time.json"

# SEPARATE TOLERANCES, because one number wearing two scales is how a check goes blind.
# A single TOL=0.05 was fine for a 58.9% share and absurd for a 0.141 transition rate —
# it tolerated 0.178 -> 0.198, a 14% error, and mutation testing caught it surviving.
TOL_PCT = 0.05  # percentage points, on values around 5-60
TOL_RATE = 0.005  # rate units, on values around 0.14-0.18


def check() -> list[str]:
    problems: list[str] = []
    if not DOC.exists():
        return [f"CANNOT CHECK: {DOC} is missing."]
    for p in (TRAJ, ARCH):
        if not p.exists():
            return [f"CANNOT CHECK: {p} is missing — regenerate assets first."]

    text = DOC.read_text(encoding="utf-8")
    traj = json.loads(TRAJ.read_text(encoding="utf-8"))
    arch = json.loads(ARCH.read_text(encoding="utf-8"))

    # ---- 1. class shares + mean career length --------------------------------
    for c in traj["classStats"]:
        name = c["class"]
        share = round(c["share"] * 100, 1)
        row = re.search(rf"^\|\s*{re.escape(name)}\s*\|([^|]*)\|([^|]*)\|", text, re.M)
        if not row:
            problems.append(f"class {name!r}: no row in the doc's career-dynamics table")
            continue
        got_share = re.search(r"([\d.]+)\s*%", row.group(1))
        if not got_share:
            problems.append(f"class {name!r}: share cell unparseable: {row.group(1)!r}")
        elif abs(float(got_share.group(1)) - share) > TOL_PCT:
            problems.append(f"class {name!r}: doc says {got_share.group(1)}%, artifact says {share}%")
        got_len = re.search(r"([\d.]+)", row.group(2))
        want_len = round(c["meanCareerLength"], 1)
        if got_len and abs(float(got_len.group(1)) - want_len) > TOL_PCT:
            problems.append(f"class {name!r} career length: doc {got_len.group(1)}, artifact {want_len}")

    # ---- 2. era transition rates ---------------------------------------------
    for r in traj["eraTransitionRates"]:
        dec, rate = r["decade"], r["meanTransitionRate"]
        m = re.search(rf"{re.escape(dec)}\D{{0,20}}?\*\*([\d.]+)\*\*", text)
        if not m:
            problems.append(f"transition rate for {dec}: not stated in the doc")
        elif abs(float(m.group(1)) - rate) > TOL_RATE:
            problems.append(f"transition rate {dec}: doc {m.group(1)}, artifact {rate}")

    # ---- 3. archetype names ---------------------------------------------------
    # The set the doc names must be the set the artifact ships. A name in the doc that
    # no asset contains is worse than a wrong number: it is vocabulary that resolves
    # to nothing.
    for name in arch["globalArchetypes"]:
        # NOT `name in text`: a substring test passes when the doc has a SUPERSTRING,
        # so renaming "Playmaking + Ball Pressure" to "...Pressures" went undetected.
        # Require the name to end at a cell/line boundary.
        if not re.search(re.escape(name) + r"\s*(?=[|\n]|$)", text):
            problems.append(
                f"archetype {name!r} is in the artifact but not the doc "
                f"(as a whole name — a superstring does not count)"
            )

    # ---- 4. player-season count ----------------------------------------------
    n = arch["n_players"]
    if not re.search(rf"{n:,}|{n}", text):
        problems.append(f"player-season count {n:,} not stated in the doc")

    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 on any drift")
    args = ap.parse_args()

    problems = check()
    if not problems:
        print("docs/ARCHETYPE_ERA_RESEARCH.md reproduces against its artifacts.")
        return 0

    print(f"{len(problems)} figure(s) in the doc do not match the artifacts:\n")
    for p in problems:
        print(f"  {p}")
    print()
    print("The artifacts are the source of truth — they are regenerated by the pipeline.")
    print("Update the DOC, not the assets, and re-run this.")
    return 1 if args.check else 0


if __name__ == "__main__":
    raise SystemExit(main())
